############################# English ############################
[en]
languageName = "En"
title = "Vintage Car Hire Melbourne"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Menu"
footer_menu_middle = "Menu"
footer_menu_right = "Menu"
#footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
