# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Cars"
url = "cars/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

[[main]]
name = "FAQ"
url = "faq/"
weight = 4

[[main]]
name = "Gallery"
url = "Gallery/"
weight = 5

# Example footer menu left
#[[footer_left]]
#name = "About Us"
#url = "#"

# Example footer menu middle
#[[footer_middle]]
#name = "Pricing"
#url = "pricing/"


# Example footer menu right
#[[footer_left]]
#name = "Privacy Policy"
#url = "privacy-policy/"

[[footer_left]]
name = "Cars"
url = "cars/"

[[footer_left]]
name = "Contact"
url = "contact/"

[[footer_left]]
name = "FAQ"
url = "faq/"

[[footer_left]]
name = "Gallery"
url = "Gallery/"
